{% set name = "pyxel-sim" %}
{% set version = "1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyxel_sim-{{ version }}.tar.gz
  sha256: 44176e81c5d9a2122f4e48b6e2556933c06c8eeb54acea41bd20fdd763e45ade

build:
  number: 0
  noarch: python
  entry_points:
    - pyxel = pyxel.run:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - setuptools >=63
    - versioneer ==0.28
    - wheel
    - pip
  run:
    - python >=3.9
    - asdf
    - astropy >=4.3
    - attrs >=21.3.0
    - bokeh
    - click
    - dask
    - distributed
    - fsspec >=2021
    - h5netcdf
    - h5py
    - holoviews >=1.15.0
    - ipywidgets >=7.5
    - matplotlib >=3.1
    - netcdf4
    - numba
    - numpy >=1.21
    - openpyxl
    - pandas
    - pillow
    - pygmo  >=2.16.1      # Added manually
    - pympler
    - pyyaml
    - scikit-image
    - scipy
    - seaborn
    - sep
    - tqdm
    - typing-extensions
    - xarray >=2022.06
    - xarray-datatree >=0.0.12
    - xlrd


test:
  imports:
    - pyxel
    - pyxel.calibration
  commands:
    - pip check
    - pyxel --help
  requires:
    - pip

about:
  home: https://esa.gitlab.io/pyxel/
  summary: Pyxel detector simulation framework.
  dev_url: https://gitlab.com/esa/pyxel
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - flemmel
    - constanzeseibert
